Cargo.toml
build.rs

But enable it by default.
This lets people opt out of building 'skeptic' and all its dependencies
if they're just trying to use the library itself, but not document or test it.
Fixes https://github.com/jeffparsons/rangemap/issues/12

Make skeptic an optional feature

---

.travis.yml
Cargo.toml
README.md

This supports the two latest stable releases.
I'm not going to bother with longer-term support for old Rust
compiler versions unless anyone indicates that they're stuck on
one for some reason.

Bump MSRV to 1.43.0

---

Cargo.toml
README.md
appveyor.yml
benches/kitchen_sink.rs
build.rs
src/inclusive_map.rs
src/inclusive_set.rs
src/lib.rs
src/map.rs
src/range_wrapper.rs
src/set.rs
src/std_ext.rs
src/stupid_range_map.rs

Uses RangeInclusive instead of Range as its keys.
This requires a bit of fiddling around with extra trait bounds
on the keys, because ranges can interact with each other by having
one range's start exactly one away from another range's end.
This requires use of the unstable Step trait (or some equivalent,
which I've introduced here) _and_ the ability to know the max
value of the key space, which I'm achieving using `num` for now.
The latter may be possible to relax with some different trickery
around the order of ranges we're comparing, and a different way
of short-circuiting some loops. I'm going to experiment with that
before committing to bringing in any extra dependency.

Add RangeInclusiveMap type

---

CHANGELOG.md
Cargo.toml
src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

Allows iterating over all sub-ranges of a given outer range that are not
covered by stored ranges.

Add `gaps` iterator for all map and set types

---

src/inclusive_map.rs
src/map.rs

Fixes https://github.com/jeffparsons/rangemap/issues/24
I'm not super-happy with this fix; even though it does address the
immediate problem, it also highlights how the complexity of this code
creates habitat for serious bugs.
What I really want is a cursor API for BTreeMap, because that would
make this entire crate nearly trivial. But I think I might be able
to rewrite a lot of it "pretending" that I have a cursor API, in a
way that would be a lot less error-prone, if slightly less performant.
So I'll give that a try when I find some time.

Fix coalescing of contiguous ranges

---

src/inclusive_map.rs
src/map.rs

This performance issue stems from the fix for #24 in d1999f4.
Previously, when the code was looking for "touching" ranges, it
applies the filter() block to at most one range (from next_back()).
But with the change in d1999f4, if none of the ranges pass the
filter, the code now potentially looks at a large number of ranges,
making insert() potentially quadratic in the map size (I think).
This patch fixes the issue by applying the "filter" to
".rev().take(2)" -- at most the two final ranges that could match.
This way, neither of the last two ranges are touching the
just-inserted range, then no more ranges are considered.
(I have verified that the tests and fuzzers still pass with this
change, but I do not know the code well enough to promise it is
correct.)

Fix a performance regression in 0.1.9.

---

src/inclusive_map.rs
src/inclusive_set.rs
src/lib.rs
src/map.rs
src/range_wrapper.rs
src/set.rs
src/std_ext.rs
src/stupid_range_map.rs

Hey there,
I have to say, this crate is very nice! In one of our projects we need support no_std, and rangemap not being marked as no_std blocks it from being used. This PR adds support for compiling only with libcore and liballoc. It could have been done by renaming all paths to core/alloc, but it ends up being rather verbose and alien, thus I added a no-std-compat crate as a dependency. It's a very thin crate with no additional dependencies. However, I could also redo the change without using external dependencies, if you would like that instead. If there are any other changes needed, I'd be glad to add them!

Add no_std support

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

Hi! I'd love to use RangeMap in a project, but I'd like to be able to consume it (to avoid cloning everything).
I added some simple `IntoIter` structs and `IntoIterator` implementations (using the equivalent `std::collections::..` types and the existing `iter()` methods as a template).
I only added a test for `RangeMap` itself, since the implementations are pretty straightforward and identical, but I can add more if you'd like. I also ran `pre-commit.sh` to test everything.
This is related to #3, as it increases feature parity with the `std` types.

Add `IntoIterator` implementations

---

src/map.rs

This PR adds implementations of the `Extend` and `FromIterator` traits for `RangeMap`. This implementation is equivalent to the one for `BTreeMap` in the standard library.

Implement Extend and FromIterator for RangeMap

---

README.fuzz.md
fuzz/Cargo.toml
fuzz/fuzz_targets/rangemap_gaps.rs
fuzz/fuzz_targets/rangemap_inclusive_gaps.rs
src/dense.rs
src/inclusive_map.rs
src/inclusive_set.rs
src/lib.rs
src/map.rs
src/set.rs

They were sometimes returning empty ranges still, and the implementation
was unnecessarily complex. There may well have been other bugs hiding in
there.
Fixes https://github.com/jeffparsons/rangemap/issues/43.
This also adds fuzzing of the gaps iterators to get a bit more confidence
that they're actually right now, including fuzzing the size of the outer
range.

Fix empty ranges returned by `Gaps` iterators

---

CHANGELOG.md
fuzz/fuzz_targets/rangemap_gaps.rs
fuzz/fuzz_targets/rangemap_inclusive_gaps.rs
src/inclusive_map.rs
src/map.rs

An empty gap is meaningless, and an empty outer range
has no values that could be considered a gap.
I've also yet again slightly simplified the gaps logic to make
it clearer what's going on.
Fixes https://github.com/jeffparsons/rangemap/issues/47

Don't yield an empty gap for an empty outer range

---

src/map.rs

Adds a test for `Gaps` iterator where the outer range lies within
the first of two stored ranges.
```
panicked at 'assertion failed: `(left == right)`
left: `Some(5..3)`,
right: `None`', src/map.rs:1239:9
```
See also issue #47

[test] Add test case that failed on v1.0.2

---

Cargo.toml
pre_commit.sh
src/lib.rs
src/map.rs
src/set.rs

Thanks for this awesome crate!
This PR makes it possible to construct a `RangeMap` and `RangeSet` in a const context without paying the overhead of `lazy_static` or similar lazy init wrappers. For example, this now works:
```rust
static MY_RANGEMAP: RangeMap<usize, String> = RangeMap::new();
```
I've gated it behind the `const_fn` feature in the Cargo.toml, because it requires a nightly compiler to enable the `const_btree_new` Rust feature. You can build it like so:
```sh
cargo +nightly build --features const_fn
```
Tested and working in Theseus OS :+1: 
I'm happy to make any requested changes.

Make `RangeMap::new()` and `RangeSet::new()` const functions.

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

Add PartialEq and Eq setups to RangeSet, RangeMap, RangeInclusiveSet and RangeInclusiveMap. This is being added so we can use this library with cosmic_text for AttrList range handling.  If you could get this in a published crate that would help us out tremendously.  This is for #https://github.com/pop-os/cosmic-text/issues/28

Add PartialEq and Eq derives

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

I have added a few Default functions that exist within the Btree.
I do think we might also add split_off, Entry, append and retain.
Also would be nice to see remove_entry that returns a removed entry/entries and to change remove to return a value/values. I will make a Issue for these.
this fixes #53 and #44

add clear, len and is_empty

---

src/inclusive_map.rs
src/inclusive_set.rs

Commit 2047d38 accidentally broke the `const_fn` feature, as the constructors for `RangeInclusiveMap::new()` and `RangeInclusiveSet::new()` didn't include a corresponding `const fn` version. This PR restores that functionality.

Make `const_fn` feature work again

---

CHANGELOG.md
src/map.rs
src/range_wrapper.rs

Returns an iterator over all stored range/value pairs that are
completely or partially overlapped by a given range.
I haven't yet added this to the all the other collection types;
want to get some feedback on this one first, and probably add
some extra testing -- maybe integrate with existing fuzz tests.

Add `overlapping` method to `RangeMap`

---

CHANGELOG.md
fuzz/fuzz_targets/rangemap_gaps.rs
fuzz/fuzz_targets/rangemap_inclusive_gaps.rs
src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/range_wrapper.rs
src/set.rs

- Misc tidy-ups, a bit more testing.
- Add `overlaps` convenience method to all collection types, which returns whether any stored range completely or partially overlaps a given range.

Add 'overlapping' and 'overlaps' methods to all container types.

---

src/map.rs
src/set.rs

Since `RangeStartWrapper` only compares the `start` of its range, two `RangeMap`s with a range with same `start` but different `end` was considered equal.
The fix here directly compares the actual both ends of the ranges.
I have also removed the `PartialOrd` and `Ord` implementations for now, but they can be reimplemented in a similar way. Let me know!

Fix `PartialEq`, `PartialOrd`, and `Ord` implementations for `RangeMap` (and `RangeSet`)

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

Instead of forcing the user of the `overlapping()` API to pass a range by reference, which causes the resulting iterator to have a lifetime which depends on this reference, the `Borrow` trait is used to give the user a choice to use either a reference or pass the range by value. The lifetime of the iterator accordingly depends on which of the two is chosen.
This pull request achieves a similar end as #70, however it does not break the existing API and allows for greater flexibility (giving the user of the API the choice of either passing the range as reference or passing a range by value.

Allow the `overlapping()` function to take ranges by value

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/range_wrapper.rs
src/set.rs

In a few places, I spotted trait implementations which are able to be replaced with automatically derived versions. I also fixed the implementations for RangeInclusiveSet to be generic over the Step functions type.
These changes pass the tests, and should not introduce any major changes, but feel free to verify.

Replaces manual trait implementations with derives

---

Cargo.toml
src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This one is more of a suggestion. I have not looked too deep into the tests, but it appears that rangemap is already very well-tested, and there is the option of using `cargo-fuzz` which is awesome.
I like to use `proptest` whenever possible, just because I quite like the interface and it gets a lot of the benefits of fuzzing for a cheaper "cost" in unit tests, and it has nice features such as test case simplification. I think it is worth using it, even if there is already a solid test interface.
This PR adds a simple proptest-based unit test for each of the set and map types as an example for how to use it. 
If you think this is useful, feel free to merge it. If not, also fine. However, it would be quite useful to have `proptest` in order to test the `intersection` functionality (that is …

Idea: use proptest additionally for unit testing

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This implements:
- `From<[Range<T>; N]>` for `RangeSet<T>`
- `From<[RangeInclusive<T>; N]>` for `RangeInclusiveSet<T>`
- `From<[(Range<K>, V); N]>` for `RangeMap<K, V>`
- `From<[(RangeInclusive<K>, V); N]>` for `RangeInclusiveMap<K, V>`
These implementations make it simpler to construct values, simply with this:
```rust
let set = RangeSet::from([0..100, 200..300]);
let set_inclusive = RangeInclusiveSet::from([0..=100, 200..=300]);
let map = RangeMap::from([(0..100, "hello"), (200..300, "world")]);
let map_inclusive = RangeInclusiveMap::from([(0..=100, "hello"), (200..=300, "world")]);
```
There are passing unit tests for each of these trait implementations.
This addresses #82.

Implements `From<[_; T]>` for set and maps

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This addresses #81 by implementing `DoubleEndedIterator` for the map and set types and adding `first()` and `last()` API functions where appropriate.
As a side-effect, this PR implements `Arbitrary` for all of the set and map types. This allows for writing more concise proptests, which I think are quite readable.

Implements `DoubleEndedIterator` for all iterators and implements `first()` and `last()` API

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This addresses issue #66 by adding macros for each of the range map data types.
For example:
```rust
use rangemap::{range_map, range_set};
// map literal
let map = range_map!{
0..100 => "abc",
200..300 => "def",
};
// set literal
let set = range_set![0..100, 300..400];
```
These macros are exported, documented and tested.

Adds a literal macro for each of the range types.

---

src/inclusive_set.rs
src/lib.rs
src/operations.rs
src/set.rs

This PR adds the ability to determine both the intersection as well as the union of two sets. It attempts to be relatively generic, working for any iterator pairs that produce sorted, but not necessarily non-overlapping ranges. 
It tries to be efficient by doing the least amount of work necessary, and correct in that it will join overlapping ranges correctly. 
Correctness is verified using randomized test cases with proptest. So far, there are test cases for:
By validating these four assumptions, we have a guarantee that the code is correct.

Intersection and Union support for sets

---

examples/roster.rs
src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/operations.rs
src/set.rs

- Removes clippy warning about needless borrow
- Changes to using non-deprecated chrono function in example
- Switches to using `From<[T]>` implementation for macro
- Tests empty macro invocation

Various fixes

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This PR simplifies a few of the unit tests and expands test coverage. It is getting close to 100% test coverage, but not quite there yet.

Expands test coverage

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

It's used in some tests to make sure that `is_empty()` returns the same value as `len() == 0`.

Allow clippy::len_zero when we really mean it

---

src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

This allows to use `Default` trait even when
generics do not implement Default.

Implement Default manually

---

Cargo.toml
src/inclusive_map.rs
src/inclusive_set.rs
src/map.rs
src/set.rs

Support quickcheck

---

src/map.rs

The RangeMap.gaps() function previously iterated
over all ranges prior to the query range before
returning the first overlapping gap. This results
in a worst-case O(n) time complexity per query.
Now the gaps() function reuses the overlaps() code to
get an iterator to the first overlapping range in O(log(n)) time.
Fixes issue #103.

Improve time complexity of gaps() function

---

src/inclusive_map.rs
src/map.rs

I didn't initially realize that the inclusive range map is a completely different implementation. Implement an O(log n) initial seek for the inclusive range map, similar to abf6bec733a5e8939cf0d9a93f0f35ed7cee3de2.

improve gaps() time complexity for inclusive range map
